# Generated by Django 4.0.1 on 2022-05-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='Taccount',
        ),
    ]
