# Generated by Django 4.0.1 on 2022-05-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taccount', '0002_rename_size_taccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taccount',
            name='account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='account'),
        ),
    ]
