# Generated by Django 4.0.1 on 2022-04-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='barangay',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='barangay'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='province'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='zip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='zip'),
        ),
    ]
