# Generated by Django 4.0.1 on 2022-05-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='username',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='city',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='province',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='zip',
        ),
    ]
