# Generated by Django 4.0.1 on 2022-05-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_rename_username_transaction_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='fullname'),
        ),
    ]
