# Generated by Django 4.0.1 on 2022-06-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_transaction_color_transaction_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='contact_number'),
        ),
    ]
