# Generated by Django 4.0.1 on 2022-06-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_transaction_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='date'),
        ),
    ]
