# Generated by Django 4.0.1 on 2022-04-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='descriptions'),
        ),
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='stocks'),
        ),
    ]
