# Generated by Django 4.0.1 on 2022-04-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_descriptions_product_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stocks',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='stocks'),
        ),
    ]
