# Generated by Django 4.0.1 on 2022-06-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numBuy',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='numBuy'),
        ),
    ]
