# Generated by Django 4.0.1 on 2022-06-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_numbuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numView',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='numView'),
        ),
    ]
