# Generated by Django 4.0.1 on 2022-05-11 03:39

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='uploads/Cases.png', upload_to=users.models.nameFile, verbose_name='image'),
        ),
    ]
