# Generated by Django 4.0.1 on 2022-06-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='user_id')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='price')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='product_name')),
                ('product_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='product_id')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('size', models.CharField(blank=True, max_length=255, null=True, verbose_name='size')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='color')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
