# Generated by Django 4.0.1 on 2022-05-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_carts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='carts',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='size'),
        ),
    ]
