# Generated by Django 4.0.1 on 2022-05-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_carts_color_carts_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='price'),
        ),
    ]
