# Generated by Django 4.0.1 on 2022-04-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='tattoo_name')),
                ('status', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='status')),
                ('quantity', models.CharField(blank=True, max_length=255, null=True, verbose_name='quantity')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
