# Generated by Django 4.0.1 on 2022-04-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryreport',
            name='status',
        ),
        migrations.AddField(
            model_name='inventoryreport',
            name='stocks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='stocks'),
        ),
    ]
