# Generated by Django 4.0.1 on 2022-04-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_report', '0002_remove_inventoryreport_status_inventoryreport_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreport',
            name='stocks',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='stocks'),
        ),
    ]
