# Generated by Django 4.0.1 on 2022-04-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_report', '0003_alter_inventoryreport_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreport',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='status'),
        ),
    ]
