# Generated by Django 4.0.1 on 2022-05-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_report', '0004_inventoryreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreport',
            name='remaining_stocks',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='remaining_stocks'),
        ),
    ]
