# Generated by Django 4.0.1 on 2022-05-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='price',
        ),
    ]
