# Generated by Django 4.0.1 on 2022-04-16 14:41

from django.db import migrations, models
import notifications.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='user_id')),
                ('viewed', models.CharField(blank=True, max_length=255, null=True, verbose_name='stocks')),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='descriptions')),
                ('image', models.ImageField(default='uploads/Cases.png', upload_to=notifications.models.nameFile, verbose_name='image')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
