# Generated by Django 4.0.1 on 2022-05-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
