# Generated by Django 4.0.1 on 2022-05-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='module',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='module'),
        ),
    ]
